.TH "guess" 1 "Guess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guess \- Guess Game 
.PP

.SH "SYNOPSIS"
.PP
\fCguess\fP [ \fI-r\fP ] 
.SH "DESCRIPTION"
.PP
The computer tries to guess a number you are thinking of (1-100)\&. 
.SH "OPTIONS"
.PP
.IP "\(bu" 2
\fC-r\fP: Enable Roman numeral mode\&. 
.PP

