/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "dummy.ts" instead.
 */

#include <check.h>

#line 1 "dummy.ts"
#include <check.h>
#include "namegen.h"

START_TEST(dummy)
{
#line 5
	ck_assert_ptr_nonnull(namegen);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, dummy);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
