/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "upstream.ts" instead.
 */

#include <check.h>

#line 1 "upstream.ts"
#include <check.h>
#include "namegen.h"

int r;
char buf[256];
int count_pass = 0;
int count_fail = 0;
unsigned long rng[] = {0xd22bfb3b};

START_TEST(alternation_test)
{
#line 13
        int i;
        int mismatch = 0;
        int seen[3] = {0, 0, 0};
        for (i = 0; i < 100; i++) {
            memset(buf, 0x5a, sizeof(buf));
            r = namegen(buf, sizeof(buf), "0|1|2", rng);
            if (r != NAMEGEN_SUCCESS || buf[1] || !strchr("012", buf[0])) {
                mismatch++;
            } else {
                seen[buf[0] - '0']++;
            }
        }
	ck_assert_int_eq(mismatch, 0);
	ck_assert_int_ne(seen[0], 0);
	ck_assert_int_ne(seen[1], 0);
	ck_assert_int_ne(seen[2], 0);

}
END_TEST
START_TEST(substitution_test)
{
#line 32
        int i;
        int mismatch = 0;
        int seen[6] = {0, 0, 0};
        for (i = 0; i < 100; i++) {
            memset(buf, 0x5a, sizeof(buf));
            r = namegen(buf, sizeof(buf), "(v)v", rng);
            if (r != NAMEGEN_SUCCESS || buf[0] != 'v' || !buf[1] || buf[2]) {
                mismatch++;
            } else {
                char *p = "aeiouy";
                char *s = strchr(p, buf[1]);
                if (!s)
                    mismatch++;
                else
                    seen[s - p]++;
            }
        }
        for (i = 0; i < 6; i++)
            mismatch += !seen[i];
	ck_assert_int_eq(mismatch, 0);
	
}
END_TEST
START_TEST(closing_bracket_test)
{
#line 56
        r = namegen(buf, sizeof(buf), "a>", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST

START_TEST(mismatch_bracket_test)
{
#line 60
        r = namegen(buf, sizeof(buf), "(a>", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST

START_TEST(unclosed_bracket_test)
{
#line 64
        r = namegen(buf, sizeof(buf), "<a", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST
START_TEST(closing_paren_test)
{
#line 69
        r = namegen(buf, sizeof(buf), "a)", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST

START_TEST(mismatch_paren_test)
{
#line 73
        r = namegen(buf, sizeof(buf), "<a)", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST

START_TEST(unclosed_paren_test)
{
#line 77
        r = namegen(buf, sizeof(buf), "(a", rng);
	ck_assert_int_eq(r, NAMEGEN_INVALID);

}
END_TEST
START_TEST(deep_nesting_test)
{
#line 83
        char *p = "(((((<(((((((((((((((a)))))))))))))))>)))))";
        memset(buf, 0x5a, sizeof(buf));
        r = namegen(buf, sizeof(buf), p, rng);
	ck_assert_int_eq(r, NAMEGEN_SUCCESS);
	ck_assert_str_eq(buf, "a");

}
END_TEST
START_TEST(truncation_1_test)
{
#line 91
        memset(buf, 0x5a, sizeof(buf));
        r = namegen(buf, 4, "(abcdefg)", rng);
	ck_assert_int_eq(r, NAMEGEN_TRUNCATED);
	ck_assert_str_eq(buf, "abc");
	ck_assert_uint_eq(buf[4], 0x5a);

}
END_TEST

START_TEST(truncation_2_test)
{
#line 98
        memset(buf, 0x5a, sizeof(buf));
        r = namegen(buf, 2, "i", rng);
	ck_assert_int_eq(r, NAMEGEN_TRUNCATED);
	ck_assert_uint_ne(buf[0], 0);
	ck_assert_uint_eq(buf[2], 0x5a);

}
END_TEST
START_TEST(capitalization_1_test)
{
#line 106
        r = namegen(buf, sizeof(buf), "!(foo)", rng);
	ck_assert_int_eq(r, NAMEGEN_SUCCESS);
	ck_assert_str_eq(buf, "Foo");

}
END_TEST

START_TEST(capitalization_2_test)
{
#line 111
        r = namegen(buf, sizeof(buf), "(!foo)", rng);
	ck_assert_int_eq(r, NAMEGEN_SUCCESS);
	ck_assert_str_eq(buf, "Foo");

}
END_TEST

START_TEST(capitalization_3_test)
{
#line 116
        r = namegen(buf, sizeof(buf), "(f!oo)", rng);
	ck_assert_int_eq(r, NAMEGEN_SUCCESS);
	ck_assert_str_eq(buf, "fOo");

}
END_TEST
START_TEST(epmty_test)
{
#line 122
        memset(buf, 0x5a, sizeof(buf));
        r = namegen(buf, sizeof(buf), "", rng);
	ck_assert_int_eq(r, NAMEGEN_SUCCESS);
	ck_assert_uint_eq(buf[0], 0);
	ck_assert_uint_eq(buf[1], 0x5a);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Tools");
    TCase *tc1_1 = tcase_create("Alternation");
    TCase *tc1_2 = tcase_create("Substitution");
    Suite *s2 = suite_create("Errors");
    TCase *tc2_1 = tcase_create("bracket");
    TCase *tc2_2 = tcase_create("paren");
    Suite *s3 = suite_create("Tools2");
    TCase *tc3_1 = tcase_create("Deep_nesting");
    TCase *tc3_2 = tcase_create("Truncation");
    TCase *tc3_3 = tcase_create("Capitalization");
    TCase *tc3_4 = tcase_create("Empty");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, alternation_test);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, substitution_test);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, closing_bracket_test);
    tcase_add_test(tc2_1, mismatch_bracket_test);
    tcase_add_test(tc2_1, unclosed_bracket_test);
    suite_add_tcase(s2, tc2_2);
    tcase_add_test(tc2_2, closing_paren_test);
    tcase_add_test(tc2_2, mismatch_paren_test);
    tcase_add_test(tc2_2, unclosed_paren_test);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, deep_nesting_test);
    suite_add_tcase(s3, tc3_2);
    tcase_add_test(tc3_2, truncation_1_test);
    tcase_add_test(tc3_2, truncation_2_test);
    suite_add_tcase(s3, tc3_3);
    tcase_add_test(tc3_3, capitalization_1_test);
    tcase_add_test(tc3_3, capitalization_2_test);
    tcase_add_test(tc3_3, capitalization_3_test);
    suite_add_tcase(s3, tc3_4);
    tcase_add_test(tc3_4, epmty_test);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
