.TH SOLVER 1 "Dec 2025" "1.0" "Solver Man Page"
.SH NAME
solver \- solve quadratic equations
.SH SYNOPSIS
.B solver
.I a b c
.SH DESCRIPTION
Solves the quadratic equation ax^2 + bx + c = 0.
.PP
Arguments must be floating point numbers.
.SH OPTIONS
None.
.SH EXIT STATUS
Returns 0 on success.
.SH SEE ALSO
bc(1)
